name: Arch Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
    # workflow_dispatch:

# env:
#   # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
#   BUILD_TYPE: Release


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v4

      - name: "Install dependencies"
        run: "pacman -Syu --noconfirm base-devel qt6-base qt6-svg qt6-multimedia cmake"

      - name: "Create build directory and run CMake"
        run: "mkdir build && cd build && \
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_TESTS=ON .."

      - name: "Build"
        run: "cd build && make"

      - name: "Run tests"
        run: "cd build && ctest --verbose --progress --output-on-failure"
      
      - name: Prepare build artifacts
        run: |
          cd build && make DESTDIR=install ./install
          cp ../LICENSE ../README.md ./install/usr/share/libremines

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libremines-build-archlinux-latest
          path: build/install