# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# env:
#   # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
#   BUILD_TYPE: Release


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-linux-qt5:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: "Apt update"
        run: "sudo apt-get update"

      - name: "Install dependencies"
        run: "sudo apt-get install build-essential qt5-default cmake libqt5svg5-dev"
      
      - name: "Create build directory and run CMake"
        run: "mkdir build && cd build && cmake .."
      
      - name: "Build"
        run: "cd build && make"

  build-linux-qt6:
    runs-on: ubuntu-20.04
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v2

      - name: "Install dependencies"
        run: "sudo pacman -Syu base-devel qt6-base qt6-svg cmake"

      - name: "Create build directory and run CMake"
        run: "mkdir build && cd build && cmake -DUSE_QT6='YES' .."

      - name: "Build"
        run: "cd build && make"
      
  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      
      - name: "Install Qt"
        uses: jurplel/install-qt-action@v2.14.0
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          dir: '${{ github.workspace }}/Qt/'
          modules: 'qtsvg'
          arch: 'win64_msvc2019_64'
          set-env: 'true'
          setup-python: 'false'

      - name: "Create build directory and run CMake"
        run: "mkdir build && cd build && cmake .."
      
      - name: "Build"
        run: "cd build && cmake --build . --config Release"

