name: Release

on:
  push:
    tags:
      - 'v*.*.*'         # Matches v1.0.0, v2.1.3, etc.
      - 'v*.*.*-*'       # Matches v1.0.0-beta, v2.1.0-rc1, etc.
  workflow_dispatch:      # Manual trigger for testing
    inputs:
      version:
        description: 'Version tag for testing (e.g., v1.0.0-test)'
        required: true
        type: string
      create_draft:
        description: 'Create as draft release'
        required: false
        type: boolean
        default: true

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      release_url: ${{ steps.create_release.outputs.upload_url }}
      release_id: ${{ steps.create_release.outputs.id }}
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Get version from tag
        id: version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: LibreMines ${{ steps.version.outputs.version }}
          draft: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.create_draft == 'true' || false }}
          prerelease: ${{ contains(steps.version.outputs.version, '-') }}
          generate_release_notes: true

  linux-appimage:
    needs: create-release
    uses: ./.github/workflows/appimage.yml
    with:
      version: ${{ needs.create-release.outputs.version }}
      upload_to_release: true

  windows-releases:
    needs: create-release
    uses: ./.github/workflows/windows-latest.yml
    with:
      version: ${{ needs.create-release.outputs.version }}
      upload_to_release: true

  macos-releases:
    needs: create-release
    uses: ./.github/workflows/macos-latest.yml
    with:
      version: ${{ needs.create-release.outputs.version }}
      upload_to_release: true