name: Windows Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
    # workflow_dispatch:

# env:
#   # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
#   BUILD_TYPE: Release


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-2022

    strategy:
      matrix:
        qt-version: [ '5.15.2', '6.5.3' ]

    steps:
      - uses: actions/checkout@v4

      - name: "Install Qt 5.15.2"
        if: matrix.qt-version == '5.15.2'
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'windows'
          dir: '${{ github.workspace }}/Qt/'
          # modules: 'qtsvg'
          arch: 'win64_msvc2019_64'
          set-env: 'true'
          setup-python: 'true'

      - name: "Install Qt 6.5.3"
        if: matrix.qt-version == '6.5.3'
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.3'
          host: 'windows'
          dir: '${{ github.workspace }}/Qt/'
          modules: 'qtmultimedia'
          arch: 'win64_msvc2019_64'
          set-env: 'true'
          setup-python: 'true'

      - name: "Create build directory and run CMake Qt 6.5.3"
        if: matrix.qt-version == '6.5.3'
        run: "mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .."

      - name: "Create build directory and run CMake Qt 5.15.2"
        if: matrix.qt-version == '5.15.2'
        run: "mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUSE_QT6='NO' .."

      - name: "Build"
        run: "cd build && cmake --build . --config Release"

      - name: Prepare build artifacts
        run: |
          New-Item -ItemType Directory -Name install
          Copy-Item -Path build/Release/libremines.exe -Destination ./install
          '${{ github.workspace }}/Qt/${{ matrix.qt-version}}' ./install
          

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libremines-build-qt-${{ matrix.qt-version }}
          path: install
