name: Windows Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
    # workflow_dispatch:

# env:
#   # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
#   BUILD_TYPE: Release


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-2022

    strategy:
      matrix:
        qt-version: [ '5.15.2', '6.5.3' ]

    steps:
      - uses: actions/checkout@v4

      - name: "Install Qt 5.15.2"
        if: matrix.qt-version == '5.15.2'
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'windows'
          dir: '${{ github.workspace }}'
          # modules: 'qtsvg'
          arch: 'win64_msvc2019_64'
          set-env: 'true'
          setup-python: 'true'

      - name: "Install Qt 6.5.3"
        if: matrix.qt-version == '6.5.3'
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.3'
          host: 'windows'
          dir: '${{ github.workspace }}'
          modules: 'qtmultimedia'
          arch: 'win64_msvc2019_64'
          set-env: 'true'
          setup-python: 'true'

      - name: "Create build directory and run CMake Qt 6.5.3"
        if: matrix.qt-version == '6.5.3'
        run: "mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .."

      - name: "Create build directory and run CMake Qt 5.15.2"
        if: matrix.qt-version == '5.15.2'
        run: "mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUSE_QT6='NO' .."

      - name: "Build"
        run: "cd build && cmake --build . --config Release"

      - name: Prepare build artifacts
        run: |
          Set-Location ./build
          ${{ github.workspace }}/Qt/${{ matrix.qt-version}}/msvc2019_64/bin/windeployqt.exe --no-translations ./Release
          Copy-Item ../README.md ./Release
          Copy-Item ../LICENSE ./Release
          New-Item -ItemType Directory ./Release/minefield_extra_themes
          Copy-Item ../share/minefield_themes/alternative_dark ./Release/minefield_extra_themes -Recurse
          Copy-Item ../share/minefield_themes/alternative_light ./Release/minefield_extra_themes -Recurse
          Copy-Item ../share/minefield_themes/flowerfield ./Release/minefield_extra_themes -Recurse
          Copy-Item ../share/minefield_themes/twemoji ./Release/minefield_extra_themes -Recurse
          New-Item -ItemType Directory ./Release/facesreaction_extra_themes
          Copy-Item ../share/faces_reaction/open-emoji-black ./Release/facesreaction_extra_themes -Recurse
          Copy-Item ../share/faces_reaction/open-emoji-white ./Release/facesreaction_extra_themes -Recurse
          Copy-Item ../share/faces_reaction/twemoji-color ./Release/facesreaction_extra_themes -Recurse
          Copy-Item ../share/faces_reaction/SecularSteve_custom ./Release/facesreaction_extra_themes -Recurse

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libremines-build-windows-qt-${{ matrix.qt-version }}
          path: build/Release
